import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import Header from "./components/header";
import Footer from "./components/footer";
import ReduxProvider from "./components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bakery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${inter.className} flex flex-col`}>
          <Header />

          <div className="flex-1">{children}</div>

          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
